### ISSUE TITLE
hopper-medium-expert-v0

### ISSUE THREAD

**Issue by logangracebrown** [rail-berkeley/d4rl#19]
1)
hopper-medium-expert-v0 has 1200919 samples.
It doesn't seem to be properly combined.

2) 
d4rl/gym_mujoco/__init__.py
kwargs in register 'ant-medium-expert-v0' doesn't have 'ref_min_score' and 'ref_max_score'.

**Comment by hiwonjoon** [comment]
I found that `hopper-medium-expert-v0` is combined with `hopper-expert` and `hopper-mixed` instead of `hopper-medium`. It can be confirmed with the script below:

```
import numpy as np
import gym, d4rl

obs_mixed  = gym.make('hopper-mixed-v0').get_dataset()['observations']
obs_expert = gym.make('hopper-expert-v0').get_dataset()['observations']
obs_medium_expert = gym.make('hopper-medium-expert-v0').get_dataset()['observations']

assert np.all(obs_medium_expert[1000000:] == obs_mixed[:]) == True
assert np.all(obs_medium_expert[:1000000] == obs_expert[:]) == True
```

When I checked the other two environments (`halfcheetah` and `walker2d`) is okay; `medium-expert` dataset is nothing but a concatenation of `medium` dataset and `expert` dataset.

It is definitely a bug and explains why BC performs so well with the environment!

**Comment by aviralkumar2907** [comment]
Hello,

Thanks for pointing this out. We have updated the dataset to include a new version as well: http://rail.eecs.berkeley.edu/datasets/offline_rl/gym_mujoco/hopper_medium_expert_v1.hdf5

We will shortly update the defaults in the code to make this change.
