### ISSUE TITLE
About the results reported in the D4RL paper table 1

### ISSUE THREAD

**Issue by ruizhaogit** [rail-berkeley/d4rl#38]
Hi guys,

I have a question about the results reported in the D4RL paper table 1.

Are these reported results the **best** undiscounted return during training averaged over multiple random seeds?
Or is it the **latset (at the 1000th training epoch?)** undiscounted return averaged over multiple random seeds?
Or is it something else?

Let me know which one did you use in the paper!

Thank you!

Best,
Rui

**Comment by justinjfu** [comment]
It's the second one - undiscounted return at the last training epoch, averaged over random seeds.

**Comment by ruizhaogit** [comment]
@justinjfu Thank you for the response! About results, I want to ask that what is the “num_eval_steps_per_epoch / evaluation frequency”, 1k or 5k? This effects the smoothing and eventually effects the final results.

**Comment by vermouth1992** [comment]
Just wonder why report the performance at the last training epoch instead of the best performance?

**Comment by justinjfu** [comment]
@ruizhaogit  Sorry for the late reply - they were set to 1000. But I noticed that the performance is pretty flat on the learning curve by the end so I don't think it will actually affect any smoothing.

@vermouth1992 Some algorithms can be noisy/unstable, so we thought it was more fair to take the average over seeds on the final epoch rather than an average over seeds on the best epoch.
