### ISSUE TITLE
Timeouts are not correct for "maze2d-umaze-v1"

### ISSUE THREAD

**Issue by koulanurag** [rail-berkeley/d4rl#85]
```python
>>> import d4rl
>>> import gym
>>> env = gym.make('maze2d-umaze-v1')
>>> dataset = env.get_dataset()
>>> np.where(dataset['timeouts']==1)
Out[4]: (array([    91,    144,    230, ..., 999592, 999702, 999868]),)
```
How can the first timeout be at `91` when the `max_episode_steps=300`, as specified over here : https://github.com/rail-berkeley/d4rl/blob/master/d4rl/pointmaze/__init__.py#L62. 

Also, shouldn't all time-outs be at an interval of `300` in this case?

**Comment by koulanurag** [comment]
```python
>>> import d4rl, gym
>>> env = gym.make('maze2d-open-v0')
>>> trajectory_dataset = sequence_dataset(env,env.get_dataset())
>>> min_traj_len = min([len(traj['rewards']) for traj in trajectory_dataset])
>>> min_traj_len
1
```

Can we have a 1 step trajectory in this env. where the terminal is only due to timeout?

**Comment by justinjfu** [comment]
This is intended behavior, although the timeout field is poorly named here. I added the following note to the Tasks wiki for this task:

The dataset consists of one continuous trajectory of the agent navigating to random goal locations, and thus has no terminal states. However, for the purposes of being able to split the trajectory into smaller subtrajectories, we use the timeout field to denote instances when the randomly selected navigation goal has been reached.

The reason for using the timeout field is that we do not want hard terminals for the qlearning_dataset function, since this would cause the environment to be non-markovian.
