### ISSUE TITLE
Error in hopper replay datasets

### ISSUE THREAD

**Issue by zhihanyang2022** [rail-berkeley/d4rl#86]
I believe I discovered a potential error for hopper in D4RL (I've fetched the latest version of the dataset). I printed out the number of terminals and timeouts, and calculated per trajectory reward as `sum of rewards / (terminals + timeouts))`.

hopper-random-v1
Terminals: 45264
Timeouts: 0
Per trajectory reward: 18.307012747437255

hopper-medium-v1
Terminals: 6327
Timeouts: 0
Per trajectory reward: 237.36670222854434

hopper-expert-v1
Terminals: 1830
Timeouts: 5
Per trajectory reward: 1889.0539509536784

hopper-medium-expert-v1
Terminals: 8157
Timeouts: 5
Per trajectory reward: 608.5970350404313

hopper-medium-replay-v1
Terminals: 849.0
Timeouts: 302.0
Per trajectory reward: 801.1659660367128

hopper-full-replay-v1
Terminals: 1907.0
Timeouts: 1000.0
Per trajectory reward: 1163.0354455031215

The replay datasets seem to be too good to be true:

For example, medium-replay has a higher per-trajectory reward than medium. Also, medium-replay reaches 302 timeouts, while medium reaches none.

For another example, full-replay shows a timeout of 1000, which means that the agent eventually learns to hit timeout consistently, which is good. However, expert only reaches a timeout of 5.

The datasets for walker2d and halfcheetah seemed fine though.

=====================

The code for printing this is here:

```python
import numpy as np
import gym
import d4rl

def print_per_traj_reward(dataset_name):
    print(dataset_name)
    env = gym.make(dataset_name)
    dataset = env.get_dataset()
    print('Terminals:', np.sum(dataset['terminals']))
    print('Timeouts:', np.sum(dataset['timeouts']))
    print('Per trajectory reward:', np.sum(dataset['rewards']) / (np.sum(dataset['terminals']) + np.sum(dataset['timeouts'])))
    print()

task_name = 'hopper'

print_per_traj_reward(f'{task_name}-random-v1')
print_per_traj_reward(f'{task_name}-medium-v1')
print_per_traj_reward(f'{task_name}-expert-v1')
print_per_traj_reward(f'{task_name}-medium-expert-v1')
print_per_traj_reward(f'{task_name}-medium-replay-v1')
print_per_traj_reward(f'{task_name}-full-replay-v1')
```

**Comment by Mr-Pepe** [comment]
And I kept wondering why I fail to train a policy that gets past 300 on the medium dataset...
Honestly, half of this benchmark is broken. It has furthermore become abandonware straight away.

**Comment by Mr-Pepe** [comment]
The mean reward for hopper-medium-v0 is twice as high as the one for hopper-medium-v1.

**Comment by zhihanyang2022** [comment]
Regrading your issue, please check out https://github.com/rail-berkeley/d4rl/issues/76, which has be solved. I think the dataset is fine as long as the authors are actively responding to community concerns...

**Comment by justinjfu** [comment]
Hi, I'm planning on regenerating the Hopper dataset in the next week or so. Sorry for the delay.

**Comment by Mr-Pepe** [comment]
@zhihanyang2022 I checked just now and the discrepancy between hopper medium v0 and v1 is still there. I think the issue you mentioned was about something else.
I do appreciate the effort to generate this benchmark. However, looking at the open issues it seems that neither are the datasets fine nor is anyone actively responding.

**Comment by zhihanyang2022** [comment]
@Mr-Pepe I see; for the discrepancy, I recommend opening a separate issue about it.

**Comment by zhihanyang2022** [comment]
@justinjfu Thanks for the effort! Have you considered opening up your code for generating the datasets? Personally, I'm happy to contribute because I believe D4RL has a lot of value.

**Comment by justinjfu** [comment]
@zhihanyang2022 Yes, that's a good suggestion. I'm setting up some time after ICML to re-organize the repository (esp. the data collection) to make things more reproducible, and I'll try to get things out this weekend.

**Comment by zhihanyang2022** [comment]
@justinjfu Thanks for the update!

**Comment by justinjfu** [comment]
I've retrained a Hopper agent and recollected new datasets. The expert should now be much improved. 

The "full replay buffer" (which contains the replay buffer up to SAC training epoch 1000) seems to be slightly worse. The # timeouts for the full replay buffer dataset will generally always be exactly 1000 due to how the training code in [rlkit](https://github.com/vitchyr/rlkit) is structured (it collects up to a fixed number of samples, and truncates).

hopper-random-v2
Terminals: 45239
Timeouts: 0
Per trajectory reward: 18.3989837308517

hopper-medium-v2
Terminals: 2185
Timeouts: 1
Per trajectory reward: 1422.1437557182069

hopper-expert-v2
Terminals: 89
Timeouts: 938
Per trajectory reward: 3513.0387049659203

hopper-medium-expert-v2
Terminals: 2274
Timeouts: 939
Per trajectory reward: 2090.4164332399628

hopper-medium-replay-v2
Terminals: 1639.0
Timeouts: 402.0
Per trajectory reward: 467.3020437857954

hopper-full-replay-v2
Terminals: 2515.0
Timeouts: 1000.0
Per trajectory reward: 827.8899075125499
